export const TASK_TYPE_EMOJIS = {
  INSPECTION: '🐝', HARVEST: '🍯', FEEDING: '🍬', ADD_SUGAR: '🍚', ADD_SYRUP: '🍮',
  DIVISION: '🔧', RENFORCEMENT: '⤴️', TREATMENT: '💊', QUEEN_CHECK: '👑',
  QUEEN_REPLACEMENT: '👑', ADD_FRAME: '🧱', REMOVE_FRAME: '🧱', ADD_SUPER: '📦',
  HIVING_TRANSFER: '🚚', FUSION: '🔀', WINTER_PREP: '❄️', OTHER: '📋',
};

export const TASK_TYPES = [
  'INSPECTION', 'DIVISION', 'RENFORCEMENT', 'FEEDING', 'ADD_SUGAR', 'ADD_SYRUP',
  'ADD_FRAME', 'REMOVE_FRAME', 'ADD_SUPER', 'TREATMENT', 'QUEEN_CHECK',
  'QUEEN_REPLACEMENT', 'HARVEST', 'HIVING_TRANSFER', 'FUSION', 'WINTER_PREP', 'OTHER',
];

export const TASK_STATUSES = ['TODO', 'IN_PROGRESS', 'DONE', 'POSTPONED', 'CANCELLED'];
export const TASK_PRIORITIES = ['LOW', 'NORMAL', 'HIGH', 'URGENT'];
